apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: valid-asyncapi-example
  description: A valid AsyncAPI 2.0 specification for testing the validator
spec:
  type: asyncapi
  lifecycle: experimental
  owner: platform-team
  definition: |
    asyncapi: 2.0.0
    info:
      title: Order Events API
      description: API for order-related events
      version: 1.0.0
    channels:
      order/created:
        description: Channel for order creation events
        subscribe:
          operationId: orderCreated
          message:
            name: OrderCreated
            payload:
              type: object
              properties:
                orderId:
                  type: string
                customerId:
                  type: string
                total:
                  type: number
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                      quantity:
                        type: integer
                      price:
                        type: number
