apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  title: ${{ values.name | title }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    {% if values.include_swagger %}
    backstage.io/api-id: ${{ values.name }}-api
    {% endif %}
spec:
  type: service
  lifecycle: development
  owner: platform-team
  {% if values.include_swagger %}
  providesApis:
    - ${{ values.name }}-api
  {% endif %}
  system: api-platform
---
{% if values.include_swagger %}
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}-api
  title: ${{ values.name | title }} API
  description: REST API for ${{ values.description }}
spec:
  type: openapi
  lifecycle: development
  owner: platform-team
  system: api-platform
  definition:
    $text: ./openapi.yaml
{% endif %}
